// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.DbContexts;

#nullable disable

namespace TestProject.Migrations
{
    [DbContext(typeof(EmployContext))]
    [Migration("20240411132402_EmploySeed")]
    partial class EmploySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TestProject.Entities.EmployEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = " ",
                            Name = "franco"
                        },
                        new
                        {
                            Id = 2,
                            Description = " ",
                            Name = "carlo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
